# Generated by Django 5.0.1 on 2024-01-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=50, null=True)),
                ('question', models.TextField(null=True)),
                ('question_type', models.CharField(max_length=20, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anser_index', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChooseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('index', models.IntegerField()),
                ('quiz_choose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.quizchoose')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFillEmpty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFillEmptyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('t_index', models.IntegerField()),
                ('f_index', models.IntegerField()),
                ('quiz_fill_empty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.quizfillempty')),
            ],
        ),
        migrations.CreateModel(
            name='QuizVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('voice_link', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Served',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.school')),
            ],
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.school')),
                ('subj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject'),
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('school', models.ManyToManyField(to='app.school')),
            ],
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='ServedPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_presence', models.BooleanField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('served', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.served')),
            ],
        ),
        migrations.CreateModel(
            name='QuizVoiceAnser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_anser', models.DateTimeField(auto_now=True)),
                ('is_right_anser', models.BooleanField(default=None, null=True)),
                ('voice_link', models.CharField(max_length=200)),
                ('quiz_voice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.quizvoice')),
                ('served', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.served')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFillEmptyOptionAnser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('index', models.IntegerField()),
                ('date_anser', models.DateTimeField(auto_now=True)),
                ('quiz_fill_empty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.quizfillempty')),
                ('served', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.served')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChooseAnser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('date_anser', models.DateTimeField(auto_now=True)),
                ('quiz_choose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.quizchoose')),
                ('served', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.served')),
            ],
        ),
    ]
