# Generated by Django 5.0.1 on 2024-01-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFillEmpty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFillEmptyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('t_index', models.IntegerField()),
                ('f_index', models.IntegerField()),
                ('quiz_fill_empty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.quizfillempty')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFillEmptyOptionAnser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('index', models.IntegerField()),
                ('date_anser', models.DateField(auto_now=True)),
                ('quiz_fill_empty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.quizfillempty')),
                ('served', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.served')),
            ],
        ),
    ]
