# Generated by Django 5.0.1 on 2024-01-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_quizfillempty_quizfillemptyoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anser_index', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChooseAnser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('date_anser', models.DateField(auto_now=True)),
                ('quiz_choose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.quizchoose')),
                ('served', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.served')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChooseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('index', models.IntegerField()),
                ('quiz_choose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.quizchoose')),
            ],
        ),
        migrations.CreateModel(
            name='QuizVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('voice_link', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizVoiceAnser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_anser', models.DateField(auto_now=True)),
                ('is_right_anser', models.BooleanField(default=None, null=True)),
                ('voice_link', models.CharField(max_length=200)),
                ('quiz_voice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.quizvoice')),
                ('served', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.served')),
            ],
        ),
    ]
