# Generated by Django 5.0.1 on 2024-01-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_quizchoose_quizchooseanser_quizchooseoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizchooseanser',
            name='date_anser',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizfillemptyoptionanser',
            name='date_anser',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizvoiceanser',
            name='date_anser',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
