# Generated by Django 5.0.1 on 2024-01-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_quizchooseanser_date_anser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizfillempty',
            options={'verbose_name': 'quiz_fill_empty'},
        ),
    ]
