# Generated by Django 5.0.1 on 2024-01-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_quizfillempty_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizfillempty',
            table='quiz_fill_empty',
        ),
    ]
